"""Adding company city

Revision ID: 80fe35026453
Revises: ebb1156f53b2
Create Date: 2018-08-15 22:15:16.015194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fe35026453'
down_revision = 'ebb1156f53b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_city', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_city')
    # ### end Alembic commands ###
