"""Adding company sate

Revision ID: e1c17210ff00
Revises: 80fe35026453
Create Date: 2018-08-21 14:03:23.075131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c17210ff00'
down_revision = '80fe35026453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_state', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_state')
    # ### end Alembic commands ###
