"""Adding zip code to company table

Revision ID: 1e5f410a1c51
Revises: aed6da14c9f5
Create Date: 2018-08-13 17:26:16.147916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5f410a1c51'
down_revision = 'aed6da14c9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_zipcode', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_zipcode')
    # ### end Alembic commands ###
